#pragma once

// #define _CRT_SECURE_NO_WARNINGS 1

//
#define INPUT_BUFFER_SIZE 4096
// #define OUTPUT_BUFFER_SIZE 4096
// #define REUSABLE_CHAR_BUFFER_SIZE 4096
// #define REUSABLE_WCHAR_BUFFER_SIZE 4096
